### ISSUE TITLE
Jobs for Jets Employer field blank

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/Jobs-For-Jets#2]
Hello, I have given access to the Jobs for Jets plugin to the woman in charge of the job postings, and she is saying that when someone uploads a job on the webiste, the employer field is blank in the dashboard, even though it is required on the fill form. So visitors are filling in the employer field, but it is not showing up in the field on the dashboard side.

I would appreciate if you could check in to this, thanks!

**Comment by joelworsham** [comment]
It seems that, for some reason, the "Employer" field was detached from any custom meta field. I've reset it.
